### ISSUE TITLE
Update to Scala 2.13

### ISSUE THREAD

**Issue by BranislavLazic** [izeigerman/parsecat#4]
Hi. I was thinking to update this repo to Scala 2.13. Keep in mind that we will have to ditch 2.11 support since most of the up-to-date dependencies are not compatible with Scala 2.11.

Complete list of updates:

- Update SBT to the latest version (1.5.4)
- Update deps to latest versions - Cats, Cats test kit, Scalatest, Discipline
- Update tests to use AnyFunSuite instead of FunSuite + "should" Matchers
- Update suites with property based testing to use `ScalaCheckPropertyChecks`

**Comment by izeigerman** [comment]
Hey @BranislavLazic , thank you so much for the issue and the PR. Apologize for taking so long to handle this. I'll be publishing the new version soon.

**Comment by izeigerman** [comment]
The [0.3.0 release](https://github.com/izeigerman/parsecat/releases/tag/v0.3.0) has been published. Thanks again!
